#!/bin/bash

rm -rf dist
mkdir -p dist

index="/tmp/index.md"

rm -f $index
touch $index

printf "# Recipes\n\n" >> $index

for f in $(find recipes -type f -regex ".*\.md")
do
 echo "Processing $f"

 # replaces .md with .html
 html="${f%.*}.html"
 # removes the recipes/ folder
 html="${html#*/}"

 # generate target file
 target="dist/$html"
 mkdir -p "$(dirname "$target")"
 pandoc -s $f -o $target

 # Uses pandoc and a custom template the extract the title from the yaml header
 title=$(pandoc "$f" --template=templates/metadata.pandoc-tpl | jq -r '.title')
 printf "* [$title]($html)\n" >> $index

done

# Generates html for index
 pandoc -s $index -o $target

