#!/bin/bash

mkdir -p dist

index="dist/index.html"

rm $index
touch $index
printf "<h1>Index</h1>\n" >> $index

printf "<ul>\n" >> $index

for f in $(find recipes -type f -regex ".*\.md")
do
 echo "Processing $f"

 # replaces .md with .html
 html="${f%.*}.html"

 # removes the recipes/ folder
 html="${html#*/}"

 title=$(yq read "$f" title)

 target="dist/$html"
 mkdir -p "$(dirname "$target")"
 pandoc -s $f -o $target
 printf "<li><a href='$html'>$title</a></li>\n" >> $index
done

printf "</ul>\n" >> $index
