#!/bin/bash

index="/tmp/index.md"
dist="site"

rm -rf "$dist"
mkdir -p "$dist"

rm -f $index
touch $index

build_folder () {
  local path=$1
  local level=$2

  local category
  category=$(basename $path)   # only keep last part of path
  category="${category^}"      # upper case first letter

  for i in $(seq 1 $level); do printf "#" >> $index; done
  printf " $category\n\n" >> $index

  # For each file on $path
  for f in $(find $path -maxdepth 1 -type f -regex ".*\.md")
  do
    echo "Processing file $f"

    local html
    html="${f%.*}.html"    # replaces .md with .html
    html="${html#*/}"      # removes the recipes/ folder

    local target
    target="$dist/$html"    # generate target file

    mkdir -p "$(dirname "$target")"
    pandoc -s -c "/pandoc.css" $f -o $target

    # Uses pandoc and a custom template the extract the title from the yaml header
    local title=$(pandoc "$f" --template=templates/metadata.pandoc-tpl | jq -r '.title')

    printf "* [$title]($html)\n" >> $index
  done

  printf "\n" >> $index

  # For each folder in $path
  for f in $(find $path -mindepth 1 -maxdepth 1 -type d)
  do
    echo "Processing path $f"
    build_folder $f $(($level+1))
  done

}

build_folder "recipes" 1

# Generates html for index
pandoc -s -c pandoc.css $index -o "$dist/index.html"

# Copy CSS
cp templates/pandoc.css $dist

