#!/bin/bash

mkdir -p recipes

args=$@
file_name=$(echo "${args// /-}" | awk '{print tolower($0)}')
full_path="recipes/$file_name.md"

printf "\n> creating $full_path"

touch $full_path
printf "\n---" >> $full_path
printf "\ntitle: $args" >> $full_path
printf "\n---\n" >> $full_path

vim $full_path
